SCRUM-2917: left aligning the column contents
alliance-genome/agr_curation pull request #1064
Opened 2023-06-06 14:30 UTC by abecerra

2023-06-06 22:13 UTC, oblodgett requested changes
Not sure where my comment went but it would be better to use bootstrap classes to do this kind of thing vs hardcoding css styles: https://primeflex.org/position

2023-06-07 20:00 UTC, oblodgett requested changes
PS Also this code has not been tested locally. He is requesting the synonyms column.

2023-06-07 20:07 UTC, oblodgett commented
https://www.primefaces.org/primeflex/alignitems
Plus the styleClass is going to go on the `ListTableCell`

2023-06-09 13:20 UTC, abecerra commented
> https://www.primefaces.org/primeflex/alignitems Plus the styleClass is going to go on the `ListTableCell`

How about making the style a parameter, with left alignment as default,  and allowing to center or right align with a style argument? [last commit]

2023-06-09 14:38 UTC, oblodgett requested changes

2023-06-09 14:38 UTC, oblodgett commented on src/main/cliapp/src/components/ListTableCell.js
> +				<li key={index} style={alignment}>
We don't need this code... we should no hardcode styles.

2023-06-09 14:44 UTC, oblodgett commented on src/main/cliapp/src/components/ListTableCell.js
> +				<li key={index} style={alignment}>
Plus this is going to change ALL ListTableCell usage... the code needs to be on the ListTableCell component not in here, styling that is.

2023-06-09 14:45 UTC, oblodgett commented on src/main/cliapp/src/components/ListTableCell.js
> +				<li key={index} style={alignment}>
This is a single line change:
```<ListTableCell template={listTemplate} listData={sortedSynonyms}/>```
change to:
 ```<ListTableCell styleClass="align-items-start" template={listTemplate} listData={sortedSynonyms}/>```

2023-06-09 14:49 UTC, oblodgett commented
This is a single line change:
```<ListTableCell template={listTemplate} listData={sortedSynonyms}/>```
change to:
 ```<ListTableCell styleClass="align-items-start" template={listTemplate} listData={sortedSynonyms}/>```

2023-06-12 11:44 UTC, abecerra commented
> This is a single line change: `<ListTableCell template={listTemplate} listData={sortedSynonyms}/>` change to: `<ListTableCell styleClass="align-items-start" template={listTemplate} listData={sortedSynonyms}/>`

The styleClass="align-items-start" in the ListTableCell left-aligns the list,

> This is a single line change: `<ListTableCell template={listTemplate} listData={sortedSynonyms}/>` change to: `<ListTableCell styleClass="align-items-start" template={listTemplate} listData={sortedSynonyms}/>`

The change produces the result in the attached capture:
![Screenshot_20230612_122250](https://github.com/alliance-genome/agr_curation/assets/143268/e93934ff-14e4-4d35-b37b-5bb0f628019e)

2023-06-12 11:46 UTC, abecerra commented
Using styleClass="align-items-start" in the  <ul> inside the ListTableCell, or even in each <li> does not change the result. The only way I was able to align the texts at the left was with { textAlign: 'left' }

2023-06-12 13:07 UTC, oblodgett commented
Sorry was wrong on which one to put the class:
On the list template:
`className='overflow-hidden text-overflow-ellipsis text-left'`

2023-06-12 14:25 UTC, abecerra commented
> Sorry was wrong on which one to put the class: On the list template: `className='overflow-hidden text-overflow-ellipsis text-left'`


it works now!

2023-06-12 14:36 UTC, oblodgett approved these changes

2023-06-12 14:36 UTC, merged