Implement species model
alliance-genome/agr_curation pull request #1332
Opened 2023-11-15 18:35 UTC by VarunReddy1111

2023-11-16 01:36 UTC, oblodgett requested changes
Sorry given that we have had changes the migration file needs to be renamed to:

`src/main/resources/db/migration/v0.29.0.2__add_species.sql`

2023-11-16 22:46 UTC, oblodgett approved these changes

2023-11-16 22:46 UTC, oblodgett commented
Good job @VarunReddy1111 your first PR!!!

2023-11-17 14:27 UTC, VarunReddy1111 commented
Thank you Olin, going ahead merging the PR.

2023-11-17 14:27 UTC, merged