Made modifications to the dataloads components and dataload service
alliance-genome/agr_curation pull request #1391
Opened 2024-01-09 21:32 UTC by VarunReddy1111

2024-01-09 21:33 UTC, oblodgett requested changes
node_modules should not be included in the PR

2024-01-09 23:57 UTC, oblodgett requested changes
package-lock.json and package.json need to get removed also

2024-01-10 14:46 UTC, adamgibs commented
@oblodgett The package.json and package-lock.json are needed to build the node_modules.

2024-01-10 14:46 UTC, oblodgett commented
@adamgibs not in the root of the project

2024-01-10 14:47 UTC, adamgibs commented
@oblodgett Ah, didn't catch that. Yeah, they shouldn't be there.

2024-01-10 14:49 UTC, oblodgett commented on package.json
> +    "file-saver": "^2.0.5"
@adamgibs @VarunReddy1111 this file needs to be removed.

2024-01-10 14:49 UTC, oblodgett commented on package-lock.json
> +{
@adamgibs @VarunReddy1111 this file needs to be removed.

2024-01-10 15:14 UTC, adamgibs approved these changes

2024-01-10 17:57 UTC, oblodgett approved these changes

2024-01-10 17:57 UTC, merged