SCRUM-3605 serialize sgdStrainBackground, add to ForPublic view
alliance-genome/agr_curation pull request #1393
Opened 2024-01-10 19:32 UTC by cmpich

2024-01-10 19:33 UTC, devopsagr requested changes

2024-01-10 19:33 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/GeneDiseaseAnnotation.java
> +	@JsonView({ View.FieldsOnly.class, View.ForPublic.class })
@cmpich this is not going to work unless its on production.

2024-01-10 19:33 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/GeneDiseaseAnnotation.java
> +	@JsonView({ View.FieldsOnly.class, View.ForPublic.class })
Sorry logged in at the wrong user. (oblodgett)

2024-01-10 19:36 UTC, oblodgett requested changes

2024-01-10 19:36 UTC, oblodgett commented on src/main/java/org/alliancegenome/curation_api/model/entities/GeneDiseaseAnnotation.java
> +	@JsonView({ View.FieldsOnly.class, View.ForPublic.class })
@cmpich this is not going to work unless its on production.

2024-01-10 20:52 UTC, cmpich commented
I also will create a new release branch with this and a corresponding PR for production. Will still need this change on alpha, though.

2024-01-11 12:41 UTC, oblodgett commented
Changes put in production get rolled back to alpha there is no need for this PR then.

2024-01-11 15:55 UTC, closed without merging