SCRUM-3952: add ExpressionPattern, TemporalContext and AnatomicalSite
alliance-genome/agr_curation pull request #1627
Opened 2024-07-26 13:53 UTC by abecerra

2024-07-29 20:05 UTC, oblodgett requested changes
You will need to rename your migration file as varun's file that just went in has the same number:
v0.36.0.6__expression_pattern.sql will need to be: v0.36.0.7__expression_pattern.sql

2024-07-31 13:19 UTC, abecerra commented
> You will need to rename your migration file as varun's file that just went in has the same number: v0.36.0.6__expression_pattern.sql will need to be: v0.36.0.7__expression_pattern.sql

File renamed and annotation ElementCollection removed

2024-07-31 13:31 UTC, oblodgett commented on src/main/java/org/alliancegenome/curation_api/model/entities/AnatomicalSite.java
> +	@JsonView({ View.FieldsOnly.class, View.ForPublic.class })
I would leave the ForPublic off that is only used for the public indexer, sorry didn't catch this before.

2024-07-31 13:34 UTC, oblodgett commented on src/main/java/org/alliancegenome/curation_api/model/entities/AnatomicalSite.java
> +	@JsonView({ View.FieldsOnly.class, View.ForPublic.class })
We will add them back in as needed but the default should be without them.

2024-07-31 15:10 UTC, abecerra commented on src/main/java/org/alliancegenome/curation_api/model/entities/AnatomicalSite.java
> +	@JsonView({ View.FieldsOnly.class, View.ForPublic.class })
Removed

2024-07-31 16:40 UTC, oblodgett approved these changes

2024-07-31 17:00 UTC, merged