SCRUM-4436 improve construct association load performance
alliance-genome/agr_curation pull request #1666
Opened 2024-09-11 13:58 UTC by cmpich

2024-09-11 13:59 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/dao/ConstructDAO.java
> +				constructIdMap.put((String) record[1], (long)record[0]);
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'typecast' is not followed by whitespace.
<!-- __reviewdog__:ChA5YzFjYzljNjYyMTdiMDQ0EgpjaGVja3N0eWxl -->

2024-09-11 13:59 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/dao/ConstructDAO.java
> +				constructIdMap.put((String) record[2], (long)record[0]);
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'typecast' is not followed by whitespace.
<!-- __reviewdog__:ChAxOTRjMzI3OTEwNGVjZjI5EgpjaGVja3N0eWxl -->

2024-09-11 13:59 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/dao/GenomicEntityDAO.java
> +				genomicEntityIdMap.put((String) record[1], (long)record[0]);
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'typecast' is not followed by whitespace.
<!-- __reviewdog__:ChA2MWNmMjY5YTg2MDBjY2ZiEgpjaGVja3N0eWxl -->

2024-09-11 13:59 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/dao/GenomicEntityDAO.java
> +				genomicEntityIdMap.put((String) record[2], (long)record[0]);
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'typecast' is not followed by whitespace.
<!-- __reviewdog__:ChBhMjE4N2E3ZDE3NDFkZDJhEgpjaGVja3N0eWxl -->

2024-09-11 14:08 UTC, oblodgett requested changes
The problem with this cache is that it gets set once for the life of the running application. So any updates will not get reflected in the map.

2024-09-11 18:44 UTC, cmpich commented
The cache only involves constructs, genes, alleles and AGMs. They do not change during the lifetime of this load. And if any of them do change in case they get updated with a load running in parallel then yes. But this load could also run out of sync without the caching. We have a general order of loads: Gene, allele, AGM then the annotations...

2024-09-12 15:47 UTC, oblodgett commented
yes but the cache is under a `@ApplicationScoped` which means it persists in memory for the duration of the server running. So in the case of production which is up for weeks. Then this cache will be out of date after the first time the load is run.

2024-09-12 15:50 UTC, oblodgett commented
If the cache was under a `RequestScoped` then yes it would be gone once the request is finished. Other items we do cache under ApplicationScoped (Organization, Ontology Terms, Dataproviders, etc) as those will almost never change. But we specially don't cache Mod objects for this very reason.

2024-09-13 15:23 UTC, cmpich commented
Changed the scope to ensure that the cache is not tied to the application running but only for the individual load run.

2024-09-13 19:50 UTC, oblodgett requested changes
Changing the scope of the DAO is not the answer. Because now every request to the DAO creates a new connection to the database. The solution should be moving the cache to the server.

2024-09-18 09:12 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/dao/ConstructDAO.java
> +import jakarta.enterprise.context.RequestScoped;
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unused import - jakarta.enterprise.context.RequestScoped.
<!-- __reviewdog__:ChBkZWQ3MWM5NTFiMzgxZmZjEgpjaGVja3N0eWxl -->

2024-09-18 09:12 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/dao/GenomicEntityDAO.java
> +import jakarta.enterprise.context.RequestScoped;
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unused import - jakarta.enterprise.context.RequestScoped.
<!-- __reviewdog__:ChBmNjk2ZWVlOTY5NzBmYzI4EgpjaGVja3N0eWxl -->

2024-09-18 09:12 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/services/GenomicEntityService.java
> +import jakarta.persistence.Query;
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unused import - jakarta.persistence.Query.
<!-- __reviewdog__:ChAzODc5NzIyY2M3YzEzMGMxEgpjaGVja3N0eWxl -->

2024-09-18 09:12 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/services/GenomicEntityService.java
> +import java.util.List;
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unused import - java.util.List.
<!-- __reviewdog__:ChBmY2ZlMWEwYzI3MzFlZDgzEgpjaGVja3N0eWxl -->

2024-09-19 14:43 UTC, oblodgett approved these changes

2024-09-19 14:52 UTC, merged