SCRUM-4426 HTPDATASAMPLE java modeling and tables creation
alliance-genome/agr_curation pull request #1684
Opened 2024-10-04 20:58 UTC by VarunReddy1111

2024-10-04 20:59 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/MicroarraySampleDetails.java
> +    @JsonView({ View.FieldsOnly.class })
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.regexp.RegexpSinglelineJavaCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Indent must use tab characters
<!-- __reviewdog__:ChBmNWE3NzBiNWVhYTYwNTFjEgpjaGVja3N0eWxl -->

2024-10-04 20:59 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/MicroarraySampleDetails.java
> +    @FullTextField(analyzer = "autocompleteAnalyzer", searchAnalyzer = "autocompleteSearchAnalyzer")
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.regexp.RegexpSinglelineJavaCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Indent must use tab characters
<!-- __reviewdog__:ChAyMzZlOTgzYjI4OTk2YjI4EgpjaGVja3N0eWxl -->

2024-10-04 20:59 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/MicroarraySampleDetails.java
> +    private String channelId;
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.regexp.RegexpSinglelineJavaCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Indent must use tab characters
<!-- __reviewdog__:ChAxMzAyMjM0OTY0MmZjMjdjEgpjaGVja3N0eWxl -->

2024-10-04 20:59 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/MicroarraySampleDetails.java
> +    @JsonView({ View.FieldsOnly.class })
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.regexp.RegexpSinglelineJavaCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Indent must use tab characters
<!-- __reviewdog__:ChAxYjlkN2VhODIwNGM5MTQ4EgpjaGVja3N0eWxl -->

2024-10-04 20:59 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/MicroarraySampleDetails.java
> +    @GenericField(projectable = Projectable.YES, sortable = Sortable.YES)
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.regexp.RegexpSinglelineJavaCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Indent must use tab characters
<!-- __reviewdog__:ChAyY2E3NmY1MWU4YTFhZGI4EgpjaGVja3N0eWxl -->

2024-10-04 20:59 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/MicroarraySampleDetails.java
> +    private Integer channelNumber;
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.regexp.RegexpSinglelineJavaCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Indent must use tab characters
<!-- __reviewdog__:ChBkZmVhYzIzYzFjMGZjMTdiEgpjaGVja3N0eWxl -->

2024-10-07 09:02 UTC, markquintontulloch requested changes
Looks good, just need to address which fields get indexed

2024-10-07 09:02 UTC, markquintontulloch commented on src/main/java/org/alliancegenome/curation_api/model/entities/BioSampleGenomicInformation.java
> +	@IndexedEmbedded(includeDepth = 1)
We may need fields indexed that are deeper than the first level.  To avoid index bloat we typically index specific paths, especially for things like Alleles that have many connections.  See the AlleleDiseaseAnnotation entity for an example of fields we typically index for alleles.  Same comment applies for the other entries in this entity class and other entity classes used here - the less fields we index the better.

2024-10-09 23:34 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/HTPExpressionDatasetSampleAnnotation.java
> +	@IndexedEmbedded(includePaths = {"bioSampleAllele.curie","bioSampleAllele.modInternalId","bioSampleAllele.modEntityId","bioSampleAllele.modEntityId_keyword",
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>',' is not followed by whitespace.
<!-- __reviewdog__:ChAzNTE1YmQ5MjliY2EwOWUxEgpjaGVja3N0eWxl -->

2024-10-09 23:34 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/HTPExpressionDatasetSampleAnnotation.java
> +	@IndexedEmbedded(includePaths = {"bioSampleAllele.curie","bioSampleAllele.modInternalId","bioSampleAllele.modEntityId","bioSampleAllele.modEntityId_keyword",
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>',' is not followed by whitespace.
<!-- __reviewdog__:ChBmNTJiMDY3M2UyZDQyOTljEgpjaGVja3N0eWxl -->

2024-10-09 23:34 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/HTPExpressionDatasetSampleAnnotation.java
> +	@IndexedEmbedded(includePaths = {"bioSampleAllele.curie","bioSampleAllele.modInternalId","bioSampleAllele.modEntityId","bioSampleAllele.modEntityId_keyword",
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>',' is not followed by whitespace.
<!-- __reviewdog__:ChAxMmVkZmM5MzA1NjI5OGY3EgpjaGVja3N0eWxl -->

2024-10-09 23:34 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/HTPExpressionDatasetSampleAnnotation.java
> +	"bioSampleAllele.modInternalId_keyword","bioSampleAgm.curie","bioSampleAgm.modInternalId","bioSampleAgm.modEntityId","bioSampleAgm.modInternalId_keyword",
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>',' is not followed by whitespace.
<!-- __reviewdog__:ChBiNTNjNzI4NjRmZjljMWM1EgpjaGVja3N0eWxl -->

2024-10-09 23:34 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/HTPExpressionDatasetSampleAnnotation.java
> +	"bioSampleAllele.modInternalId_keyword","bioSampleAgm.curie","bioSampleAgm.modInternalId","bioSampleAgm.modEntityId","bioSampleAgm.modInternalId_keyword",
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>',' is not followed by whitespace.
<!-- __reviewdog__:ChBlMTNiNTFlNTFiYWMzZGExEgpjaGVja3N0eWxl -->

2024-10-09 23:34 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/HTPExpressionDatasetSampleAnnotation.java
> +	"bioSampleAllele.modInternalId_keyword","bioSampleAgm.curie","bioSampleAgm.modInternalId","bioSampleAgm.modEntityId","bioSampleAgm.modInternalId_keyword",
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>',' is not followed by whitespace.
<!-- __reviewdog__:ChA5NTc5OTk3NTJjZTBhZDk2EgpjaGVja3N0eWxl -->

2024-10-09 23:34 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/HTPExpressionDatasetSampleAnnotation.java
> +	"bioSampleAllele.modInternalId_keyword","bioSampleAgm.curie","bioSampleAgm.modInternalId","bioSampleAgm.modEntityId","bioSampleAgm.modInternalId_keyword",
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>',' is not followed by whitespace.
<!-- __reviewdog__:ChBmNWQ4MjMxODMxYmQ0MGUzEgpjaGVja3N0eWxl -->

2024-10-09 23:34 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/HTPExpressionDatasetSampleAnnotation.java
> +	"bioSampleAgm.modEntityId_keyword","bioSampleAllele.curie_keyword","bioSampleAgm.curie_keyword","bioSampleText","bioSampleText_keyword"})
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.regexp.RegexpSinglelineJavaCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Line must not have trailing whitespace
<!-- __reviewdog__:ChA4YWZmZjg5N2Y3MDI0YWI3EgpjaGVja3N0eWxl -->

2024-10-09 23:34 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/HTPExpressionDatasetSampleAnnotation.java
> +	"bioSampleAgm.modEntityId_keyword","bioSampleAllele.curie_keyword","bioSampleAgm.curie_keyword","bioSampleText","bioSampleText_keyword"})
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>',' is not followed by whitespace.
<!-- __reviewdog__:ChAyZDIxMzY5OTY3Y2U2ODFmEgpjaGVja3N0eWxl -->

2024-10-09 23:34 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/HTPExpressionDatasetSampleAnnotation.java
> +	"bioSampleAgm.modEntityId_keyword","bioSampleAllele.curie_keyword","bioSampleAgm.curie_keyword","bioSampleText","bioSampleText_keyword"})
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>',' is not followed by whitespace.
<!-- __reviewdog__:ChAzNTJlZjU5MTdjNWZlNTllEgpjaGVja3N0eWxl -->

2024-10-09 23:34 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/HTPExpressionDatasetSampleAnnotation.java
> +	"bioSampleAgm.modEntityId_keyword","bioSampleAllele.curie_keyword","bioSampleAgm.curie_keyword","bioSampleText","bioSampleText_keyword"})
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>',' is not followed by whitespace.
<!-- __reviewdog__:ChA0YzMxZGFkY2RkODczYjBkEgpjaGVja3N0eWxl -->

2024-10-09 23:34 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/HTPExpressionDatasetSampleAnnotation.java
> +	"bioSampleAgm.modEntityId_keyword","bioSampleAllele.curie_keyword","bioSampleAgm.curie_keyword","bioSampleText","bioSampleText_keyword"})
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>',' is not followed by whitespace.
<!-- __reviewdog__:ChA1ODM1MzM1MjMwZmY4MjBiEgpjaGVja3N0eWxl -->

2024-10-09 23:34 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/HTPExpressionDatasetSampleAnnotation.java
> +	@IndexedEmbedded(includePaths = {"channelId","channelId_keyword"})
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>',' is not followed by whitespace.
<!-- __reviewdog__:ChA1YjcwZGIzNDQwZjQ0YzYzEgpjaGVja3N0eWxl -->

2024-10-09 23:34 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/BioSampleAge.java
> +	@IndexedEmbedded(includePaths = {"age","age_keyword"})
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>',' is not followed by whitespace.
<!-- __reviewdog__:ChA2Y2M2MGU0N2ZhMmFkMTBiEgpjaGVja3N0eWxl -->

2024-10-09 23:38 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/HTPExpressionDatasetSampleAnnotation.java
> +	@IndexedEmbedded(includePaths = {"bioSampleAllele.curie", "bioSampleAllele.modInternalId", "bioSampleAllele.modEntityId","bioSampleAllele.modEntityId_keyword",
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>',' is not followed by whitespace.
<!-- __reviewdog__:ChA4MTRjMDBlMGViMDdhNmYzEgpjaGVja3N0eWxl -->

2024-10-09 23:38 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/HTPExpressionDatasetSampleAnnotation.java
> +	})
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.regexp.RegexpSinglelineJavaCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Line must not have trailing whitespace
<!-- __reviewdog__:Cg8zYzExZjUwYjIxYWU0MjkSCmNoZWNrc3R5bGU= -->

2024-10-09 23:38 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/HTPExpressionDatasetSampleAnnotation.java
> +	@IndexedEmbedded(includePaths = {"channelId","channelId_keyword"})
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>',' is not followed by whitespace.
<!-- __reviewdog__:ChA1OWVjYjljNWNjMTY1ODAzEgpjaGVja3N0eWxl -->

2024-10-10 23:13 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/HTPExpressionDatasetSampleAnnotation.java
> +	@IndexedEmbedded( includePaths = {"curie", "preferredCrossReference.referencedCurie", "secondaryIdentifiers",
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.ParenPadCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'(' is followed by whitespace.
<!-- __reviewdog__:ChA3ZDA5YThlZTAwYjY3MTgzEgpjaGVja3N0eWxl -->

2024-10-10 23:13 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/HTPExpressionDatasetSampleAnnotation.java
> +	@IndexedEmbedded( includePaths = {"curie", "preferredCrossReference.referencedCurie", "secondaryIdentifiers",
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.ParenPadCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'(' is followed by whitespace.
<!-- __reviewdog__:Cg9iYzdiMDJlOGU1NDI4NjYSCmNoZWNrc3R5bGU= -->

2024-10-14 14:46 UTC, markquintontulloch approved these changes

2024-10-14 15:05 UTC, merged

2024-10-14 15:49 UTC, oblodgett commented on src/main/java/org/alliancegenome/curation_api/model/entities/BioSampleGenomicInformation.java
> +@Indexed
@VarunReddy1111 I don't see the indexes defined for this table?

2024-10-14 15:50 UTC, oblodgett commented on src/main/java/org/alliancegenome/curation_api/model/entities/HTPExpressionDatasetSampleAnnotation.java
> +})
@VarunReddy1111 I think there is a bunch of missing indexes here not defined in the code.

2024-10-14 15:52 UTC, oblodgett commented on src/main/resources/db/migration/v0.37.0.59__htpdatasample_tables.sql
> +ALTER TABLE biosamplegenomicinformation
@VarunReddy1111 everyy single one of these FK's needs to have a corresponding index.