SCRUM-4509 Validation of HTPExpressionDataSampleAnnotation
alliance-genome/agr_curation pull request #1698
Opened 2024-10-29 04:02 UTC by VarunReddy1111

2024-10-29 04:03 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/dao/HTPExpressionDatasetSampleAnnotationDAO.java
> +
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.regexp.RegexpSinglelineJavaCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Indent must use tab characters
<!-- __reviewdog__:ChAyYzZiNGUxZDA1YjkyNTQxEgpjaGVja3N0eWxl -->

2024-10-29 04:03 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/dao/HTPExpressionDatasetSampleAnnotationDAO.java
> +    protected HTPExpressionDatasetSampleAnnotationDAO() {
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.regexp.RegexpSinglelineJavaCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Indent must use tab characters
<!-- __reviewdog__:ChA0Y2VjMTk0YTQ0Zjk4NDA3EgpjaGVja3N0eWxl -->

2024-10-29 04:03 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/ingest/dto/fms/BioSampleGenomicInformationDTO.java
> +public class BioSampleGenomicInformationDTO extends BaseDTO{
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAroundCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'{' is not preceded with whitespace.
<!-- __reviewdog__:ChAyODUwYzI3MDA4YTg5YmM4EgpjaGVja3N0eWxl -->

2024-10-29 04:03 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/ingest/dto/fms/MicroarraySampleDetailsDTO.java
> +public class MicroarraySampleDetailsDTO extends BaseDTO{
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAroundCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'{' is not preceded with whitespace.
<!-- __reviewdog__:ChBmZmRlMTZlZmE2NThiNjkzEgpjaGVja3N0eWxl -->

2024-10-29 04:03 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/ingest/dto/fms/HTPExpressionDatasetSampleAnnotationFmsDTO.java
> +public class HTPExpressionDatasetSampleAnnotationFmsDTO extends BaseDTO{
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAroundCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'{' is not preceded with whitespace.
<!-- __reviewdog__:ChBjMzkwODA1ZWYxOTEyNGZlEgpjaGVja3N0eWxl -->

2024-10-29 04:03 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/ingest/dto/fms/HTPExpressionDatasetSampleAnnotationIngestFmsDTO.java
> +public class HTPExpressionDatasetSampleAnnotationIngestFmsDTO extends BaseDTO{
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAroundCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'{' is not preceded with whitespace.
<!-- __reviewdog__:ChBhOTVhYTcwNGYwOTY1ZGIxEgpjaGVja3N0eWxl -->

2024-10-29 04:03 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/ingest/dto/fms/HTPExpressionDatasetSampleAnnotationIngestFmsDTO.java
> +    private MetaDataFmsDTO metaData;
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.regexp.RegexpSinglelineJavaCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Indent must use tab characters
<!-- __reviewdog__:ChA2Y2RkNzJiMDU2OTgwNzUzEgpjaGVja3N0eWxl -->

2024-10-29 04:03 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/jobs/executors/BulkLoadJobExecutor.java
> +		} else if(bulkLoadFileHistory.getBulkLoad().getBackendBulkLoadType() == BackendBulkLoadType.HTPDATASAMPLE) {
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAroundCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'if' is not followed by whitespace.
<!-- __reviewdog__:ChAzOGI3MzQyYWNiMmNjMDBlEgpjaGVja3N0eWxl -->

2024-10-29 04:03 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/jobs/executors/HTPExpressionDatasetSampleAnnotationExecutor.java
> +public class HTPExpressionDatasetSampleAnnotationExecutor extends LoadFileExecutor{
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAroundCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'{' is not preceded with whitespace.
<!-- __reviewdog__:ChA1YjlmZTI2MjBjMjA3Yzk1EgpjaGVja3N0eWxl -->

2024-10-29 04:03 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/jobs/executors/HTPExpressionDatasetSampleAnnotationExecutor.java
> +    public void execLoad(BulkLoadFileHistory bulkLoadFileHistory) {
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.regexp.RegexpSinglelineJavaCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Indent must use tab characters
<!-- __reviewdog__:ChA3MzhjNmYwMDQ3MTE4MmVmEgpjaGVja3N0eWxl -->

2024-10-29 04:03 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/jobs/executors/HTPExpressionDatasetSampleAnnotationExecutor.java
> +        try {
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.regexp.RegexpSinglelineJavaCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Indent must use tab characters
<!-- __reviewdog__:ChAzNWUzMjlmNjUyMWU2MTc1EgpjaGVja3N0eWxl -->

2024-10-29 04:03 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/jobs/executors/HTPExpressionDatasetSampleAnnotationExecutor.java
> +    }
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.regexp.RegexpSinglelineJavaCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Indent must use tab characters
<!-- __reviewdog__:ChBlNmI1MzcxMjE1ZTNjMGIzEgpjaGVja3N0eWxl -->

2024-10-29 04:22 UTC, VarunReddy1111 commented
Having conflict in migration file version with other PR, will change the version of this PR, if the other PR goes in first. If this PR goes first, will update the migration version of the  other PR after checking with Christian.

2024-10-29 08:18 UTC, markquintontulloch requested changes
Looks good, just a few small changes requested

2024-10-29 08:18 UTC, markquintontulloch commented on src/main/java/org/alliancegenome/curation_api/jobs/executors/HTPExpressionDatasetSampleAnnotationExecutor.java
> +	private boolean runLoad(BulkLoadFileHistory history, BackendBulkDataProvider dataProvider, List<HTPExpressionDatasetSampleAnnotationFmsDTO> htpDatasetSampleAnnotations, List<Long> htpAnnotationsIdsL
I think we should be able to use the generic runLoad method here?

2024-10-29 08:18 UTC, markquintontulloch commented on src/main/java/org/alliancegenome/curation_api/model/entities/HTPExpressionDatasetSampleAnnotation.java
> +	@ManyToMany(cascade = CascadeType.ALL)
Probably also want `orphanRemove = true` here

2024-10-29 08:18 UTC, markquintontulloch commented on src/main/java/org/alliancegenome/curation_api/model/ingest/dto/fms/BioSampleAgeDTO.java
> +	private WhenExpressedDTO stage;
I know this isn't your code, but could we rename the WhenExpressedDTO and WhereExpressedDTO classes to WhenExpressedFmsDTO and WhereExpressedFmsDTO respectively.  That makes it clear that these are not expected to align with the LinkML schema.

2024-10-29 08:18 UTC, markquintontulloch commented on src/main/java/org/alliancegenome/curation_api/model/ingest/dto/fms/BioSampleGenomicInformationDTO.java
> +public class BioSampleGenomicInformationDTO extends BaseDTO {
Should be rename to BioSampleGenomicInformationFmsDTO

2024-10-29 08:18 UTC, markquintontulloch commented on src/main/java/org/alliancegenome/curation_api/model/ingest/dto/fms/MicroarraySampleDetailsDTO.java
> +public class MicroarraySampleDetailsDTO extends BaseDTO {
Should be renamed to MicroarraySampleDetailsFmsDTO

2024-10-29 08:18 UTC, markquintontulloch commented on src/main/java/org/alliancegenome/curation_api/services/validation/dto/fms/HTPExpressionDatasetSampleAnnotationFmsDTOValidator.java
> +		if (dto.getSampleId().getPrimaryId() != null) {
I prefer to use StringUtils.isNotBlank for checks on strings as it rules out empty or whitespace-only strings as well as nulls.

2024-10-29 16:02 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/jobs/executors/HTPExpressionDatasetSampleAnnotationExecutor.java
> +import org.alliancegenome.curation_api.exceptions.ObjectUpdateException;
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unused import - org.alliancegenome.curation_api.exceptions.ObjectUpdateException.
<!-- __reviewdog__:ChAxZTZmNzAzMWU2ZGVlZjY2EgpjaGVja3N0eWxl -->

2024-10-29 16:02 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/jobs/executors/HTPExpressionDatasetSampleAnnotationExecutor.java
> +import org.alliancegenome.curation_api.exceptions.ObjectUpdateException.ObjectUpdateExceptionData;
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unused import - org.alliancegenome.curation_api.exceptions.ObjectUpdateException.ObjectUpdateExceptionData.
<!-- __reviewdog__:Cg9kYzhiYWNmODE3MzZkNDYSCmNoZWNrc3R5bGU= -->

2024-10-29 16:02 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/jobs/executors/HTPExpressionDatasetSampleAnnotationExecutor.java
> +import org.alliancegenome.curation_api.model.ingest.dto.fms.HTPExpressionDatasetSampleAnnotationFmsDTO;
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unused import - org.alliancegenome.curation_api.model.ingest.dto.fms.HTPExpressionDatasetSampleAnnotationFmsDTO.
<!-- __reviewdog__:ChA1ZDVjNWZjYjJkM2E2OGI2EgpjaGVja3N0eWxl -->

2024-10-29 16:02 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/jobs/executors/HTPExpressionDatasetSampleAnnotationExecutor.java
> +import org.alliancegenome.curation_api.util.ProcessDisplayHelper;
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unused import - org.alliancegenome.curation_api.util.ProcessDisplayHelper.
<!-- __reviewdog__:ChBkNDM5ZDJhMDVkZmYxN2U1EgpjaGVja3N0eWxl -->

2024-10-29 16:02 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/jobs/executors/HTPExpressionDatasetSampleAnnotationExecutor.java
> +import io.quarkus.logging.Log;
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unused import - io.quarkus.logging.Log.
<!-- __reviewdog__:ChBjMTIzZWUyYmFmNjQzMTA2EgpjaGVja3N0eWxl -->

2024-10-29 17:19 UTC, markquintontulloch approved these changes

2024-10-31 14:17 UTC, oblodgett approved these changes

2024-10-31 16:49 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/services/validation/dto/fms/HTPExpressionDatasetSampleAnnotationFmsDTOValidator.java
> +			if(CollectionUtils.isNotEmpty(htpSampleAnnotation.getHtpExpressionSampleLocations())) {
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAroundCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'if' is not followed by whitespace.
<!-- __reviewdog__:ChA0N2M0MGY4YzlkNzE0NGNkEgpjaGVja3N0eWxl -->

2024-10-31 20:39 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/services/validation/dto/fms/HTPExpressionDatasetSampleAnnotationFmsDTOValidator.java
> +		Boolean sampleExists = ((dto.getSampleId() != null && StringUtils.isNotEmpty(dto.getSampleId().getPrimaryId())) || StringUtils.isNotEmpty(dto.getSampleTitle()));
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.coding.UnnecessaryParenthesesCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unnecessary parentheses around assignment right-hand side.
<!-- __reviewdog__:ChBhZmU5MDUxNzFkYjVhNjE1EgpjaGVja3N0eWxl -->

2024-10-31 20:39 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/services/validation/dto/fms/HTPExpressionDatasetSampleAnnotationFmsDTOValidator.java
> +		Boolean sampleExists = ((dto.getSampleId() != null && StringUtils.isNotEmpty(dto.getSampleId().getPrimaryId())) || StringUtils.isNotEmpty(dto.getSampleTitle()));
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.coding.UnnecessaryParenthesesCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unnecessary parentheses around expression.
<!-- __reviewdog__:ChA1Y2U3MGI1NzBlMGE1YzY1EgpjaGVja3N0eWxl -->

2024-10-31 20:39 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/services/validation/dto/fms/HTPExpressionDatasetSampleAnnotationFmsDTOValidator.java
> +		if(!sampleExists) {
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAroundCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'if' is not followed by whitespace.
<!-- __reviewdog__:ChA2MTI2NjU1MDY5YTRiN2U5EgpjaGVja3N0eWxl -->

2024-10-31 20:39 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/services/validation/dto/fms/HTPExpressionDatasetSampleAnnotationFmsDTOValidator.java
> +			Boolean genomicInformationExists = (StringUtils.isNotEmpty(dto.getGenomicInformation().getBioSampleText()) == true || StringUtils.isNotEmpty(dto.getGenomicInformation().getBiosampleId()) == true);
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.coding.UnnecessaryParenthesesCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unnecessary parentheses around assignment right-hand side.
<!-- __reviewdog__:ChA5YzUxNmFjNDVhNjRkZDk4EgpjaGVja3N0eWxl -->

2024-10-31 20:39 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/services/validation/dto/fms/HTPExpressionDatasetSampleAnnotationFmsDTOValidator.java
> +			Boolean genomicInformationExists = (StringUtils.isNotEmpty(dto.getGenomicInformation().getBioSampleText()) == true || StringUtils.isNotEmpty(dto.getGenomicInformation().getBiosampleId()) == true);
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.coding.SimplifyBooleanExpressionCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expression can be simplified.
<!-- __reviewdog__:ChA0ZDgzNGEyMzM5NmIwY2U4EgpjaGVja3N0eWxl -->

2024-10-31 20:39 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/services/validation/dto/fms/HTPExpressionDatasetSampleAnnotationFmsDTOValidator.java
> +			Boolean genomicInformationExists = (StringUtils.isNotEmpty(dto.getGenomicInformation().getBioSampleText()) == true || StringUtils.isNotEmpty(dto.getGenomicInformation().getBiosampleId()) == true);
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.coding.SimplifyBooleanExpressionCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expression can be simplified.
<!-- __reviewdog__:ChBlMDdmOTE4Njg5MTNkMTgxEgpjaGVja3N0eWxl -->

2024-10-31 20:43 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/services/validation/dto/fms/HTPExpressionDatasetSampleAnnotationFmsDTOValidator.java
> +		Boolean sampleExists = (dto.getSampleId() != null && StringUtils.isNotEmpty(dto.getSampleId().getPrimaryId()) || StringUtils.isNotEmpty(dto.getSampleTitle()));
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.coding.UnnecessaryParenthesesCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unnecessary parentheses around assignment right-hand side.
<!-- __reviewdog__:ChBhZmU5MDUxNzFkYjVhNjE1EgpjaGVja3N0eWxl -->

2024-10-31 20:43 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/services/validation/dto/fms/HTPExpressionDatasetSampleAnnotationFmsDTOValidator.java
> +			Boolean genomicInformationExists = (StringUtils.isNotEmpty(dto.getGenomicInformation().getBioSampleText()) == true) || (StringUtils.isNotEmpty(dto.getGenomicInformation().getBiosampleId()) == true
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.coding.UnnecessaryParenthesesCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unnecessary parentheses around expression.
<!-- __reviewdog__:ChA0MmYyNjZiNDQ2ZDViZTQ4EgpjaGVja3N0eWxl -->

2024-10-31 20:43 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/services/validation/dto/fms/HTPExpressionDatasetSampleAnnotationFmsDTOValidator.java
> +			Boolean genomicInformationExists = (StringUtils.isNotEmpty(dto.getGenomicInformation().getBioSampleText()) == true) || (StringUtils.isNotEmpty(dto.getGenomicInformation().getBiosampleId()) == true
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.coding.SimplifyBooleanExpressionCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expression can be simplified.
<!-- __reviewdog__:ChA0ZDgzNGEyMzM5NmIwY2U4EgpjaGVja3N0eWxl -->

2024-10-31 20:43 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/services/validation/dto/fms/HTPExpressionDatasetSampleAnnotationFmsDTOValidator.java
> +			Boolean genomicInformationExists = (StringUtils.isNotEmpty(dto.getGenomicInformation().getBioSampleText()) == true) || (StringUtils.isNotEmpty(dto.getGenomicInformation().getBiosampleId()) == true
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.coding.UnnecessaryParenthesesCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unnecessary parentheses around expression.
<!-- __reviewdog__:ChBlMjZmZmZiODk3MDYwMjJlEgpjaGVja3N0eWxl -->

2024-10-31 20:43 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/services/validation/dto/fms/HTPExpressionDatasetSampleAnnotationFmsDTOValidator.java
> +			Boolean genomicInformationExists = (StringUtils.isNotEmpty(dto.getGenomicInformation().getBioSampleText()) == true) || (StringUtils.isNotEmpty(dto.getGenomicInformation().getBiosampleId()) == true
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.coding.SimplifyBooleanExpressionCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expression can be simplified.
<!-- __reviewdog__:ChBmMzlhNDhlOWI2NGFkM2MxEgpjaGVja3N0eWxl -->

2024-10-31 20:53 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/services/validation/dto/fms/HTPExpressionDatasetSampleAnnotationFmsDTOValidator.java
> +		Boolean sampleExists = (dto.getSampleId() != null && StringUtils.isNotEmpty(dto.getSampleId().getPrimaryId())) || StringUtils.isNotEmpty(dto.getSampleTitle());
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.coding.UnnecessaryParenthesesCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unnecessary parentheses around expression.
<!-- __reviewdog__:ChA3MDUxY2NlYzUwYTdhZjdkEgpjaGVja3N0eWxl -->

2024-11-01 12:37 UTC, abecerra approved these changes

2024-11-01 14:21 UTC, merged