SCRUM-4634: production release/v0.36.0
alliance-genome/agr_curation pull request #1754
Opened 2024-12-06 15:50 UTC by abecerra

2024-12-06 16:06 UTC, VarunReddy1111 approved these changes

2024-12-06 16:15 UTC, oblodgett requested changes
i thought we were doing alpha to beta today?

2024-12-06 16:23 UTC, abecerra commented
> i thought we were doing alpha to beta today?

Beta is deployed now!. 
This is to deploy on Monday if Chris signs up beta, but it could wait if needed

2024-12-08 02:27 UTC, oblodgett commented
ahh ok

2024-12-08 02:27 UTC, oblodgett approved these changes

2024-12-12 16:46 UTC, closed without merging