SCRUM-4646 add synonym loading for AGMs
alliance-genome/agr_curation pull request #1768
Opened 2024-12-13 19:15 UTC by cmpich

2024-12-13 19:16 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/ingest/dto/AffectedGenomicModelDTO.java
> +import org.alliancegenome.curation_api.model.ingest.dto.slotAnnotions.NameSlotAnnotationDTO;
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unused import - org.alliancegenome.curation_api.model.ingest.dto.slotAnnotions.NameSlotAnnotationDTO.
<!-- __reviewdog__:ChBjZWU4NGUxZTIzM2Y3MTk3EgpjaGVja3N0eWxl -->

2024-12-13 19:16 UTC, devopsagr commented on src/main/java/org/alliancegenome/curation_api/model/entities/AffectedGenomicModel.java
> +	@JsonView({ View.FieldsAndLists.class, View.AffectedGenomicModelView.class  })
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.SingleSpaceSeparatorCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Use a single space to separate non-whitespace characters.
<!-- __reviewdog__:ChBkM2IxMDcyNmJhYzc4YjZmEgpjaGVja3N0eWxl -->

2024-12-13 21:37 UTC, markquintontulloch requested changes
Looks good but field needs adding to integration tests and test files

2024-12-16 16:59 UTC, markquintontulloch commented
@cmpich The AGM bulk load tests and test files need updating too

2024-12-17 10:55 UTC, markquintontulloch approved these changes

2024-12-17 16:29 UTC, merged