UI reskin
alliance-genome/agr_curation pull request #305
Opened 2022-02-25 16:24 UTC by adamgibs

2022-02-25 17:17 UTC, oblodgett requested changes
I think we need to go through the assets/demo directory and get rid of stuff that we don't need.... there are a lot of large pictures in there etc.

2022-02-25 17:17 UTC, oblodgett commented on src/main/cliapp/gulpfile.js
> -});
@adamgibs I do believe we are going to need this file for building the app... would need to verify.

2022-02-25 17:17 UTC, oblodgett commented on src/main/cliapp/public/assets/demo/data/customers-large.json
> -
This file probably needs to be deleted.

2022-02-25 17:17 UTC, oblodgett commented on src/main/cliapp/public/assets/demo/data/customers-medium.json
> -
This file probably needs to be deleted.

2022-02-25 17:17 UTC, oblodgett commented on src/main/cliapp/public/assets/demo/data/events.json
> -    		"start": "2023-01-03"
This file probably needs to be deleted?

2022-02-25 17:17 UTC, oblodgett commented on src/main/cliapp/public/assets/demo/data/photos.json
> +{
This file probably needs to be deleted?

2022-02-25 17:17 UTC, oblodgett commented on src/main/cliapp/public/index.html
> +        <title>PrimeReact - Sakai</title>
Probably should fix this.

2022-02-25 17:25 UTC, adamgibs commented
@oblodgett Yeah, that makes sense to me. Do we need anything from that directory? Seems like public/asses/demo could just be totally wiped.

2022-03-03 17:51 UTC, oblodgett approved these changes

2022-03-07 21:37 UTC, merged