SCRUM-1676 refactored AutocompleteEditor template
alliance-genome/agr_curation pull request #547
Opened 2022-07-08 19:51 UTC by adamgibs

- moved tooltip filtering into utility function
  - added autocomplete templates
  - added onSelectionOver to utils
  - moved AutocompleteEditor and templates into Autocomplete folder
  - deleted SingleOntologyEditor and SingleOntologyTooltip

2022-07-12 16:12 UTC, oblodgett requested changes

2022-07-12 16:12 UTC, oblodgett commented on src/main/cliapp/src/components/Autocomplete/AutocompleteEditor.js
> +		console.log(rowProps.rowIndex);
Can re remove these logs?

2022-07-13 23:29 UTC, adamgibs commented
@oblodgett Log lines have been removed.

2022-07-14 14:42 UTC, oblodgett approved these changes

2022-07-14 14:48 UTC, merged