SCRUM-2446 WB Phenotype ontology loading
alliance-genome/agr_curation pull request #943
Opened 2023-02-28 18:27 UTC by mluypaert

2023-02-28 18:55 UTC, oblodgett approved these changes

2023-02-28 19:11 UTC, markquintontulloch requested changes
Can we make the case of the various class names consistent - you have Wbphenotype for DAO and controller, but WbPhenotype for interface.  Also is WBPheno an acceptable abbreviation?  If so, we should probably use this abbreviation for the entity class for consistency (i.e. WBPhenoTerm).

2023-03-01 12:47 UTC, mluypaert commented
> Can we make the case of the various class names consistent - you have Wbphenotype for DAO and controller, but WbPhenotype for interface. Also is WBPheno an acceptable abbreviation? If so, we should probably use this abbreviation for the entity class for consistency (i.e. WBPhenoTerm).

I've now unified the casing of all WB Phenotype Term classes, the decision to abbriate all classnames or not is up to @chris-grove I think. The abbreviated form `WBPheno` makes more sense on the dashboard and the data type selection, as that benefits from shorter names.

2023-03-01 13:01 UTC, markquintontulloch approved these changes

2023-03-01 13:11 UTC, merged