SCRUM-2761
alliance-genome/agr_curation pull request #983
Opened 2023-03-28 10:05 UTC by markquintontulloch

2023-03-28 13:03 UTC, oblodgett requested changes

2023-03-28 13:03 UTC, oblodgett commented on src/main/cliapp/src/containers/dataLoadsPage/DataLoadsComponent.js
> -			ret.push(<Column key="fmsDataType2" field="fmsDataType" header="Load Data Type" />);
The field name for the FMS load did not change, not should it. See `BulkFMSLoad.java`

2023-03-28 13:03 UTC, oblodgett commented on src/main/java/org/alliancegenome/curation_api/jobs/executors/LoadFileExecutor.java
> -	public void runCleanup(DiseaseAnnotationService service, BulkLoadFileHistory history, String speciesName, List<Long> annotationIdsBefore, List<Long> annotationIdsAfter) {
Thanks for catching this I thought I got all of them.

2023-03-28 13:03 UTC, oblodgett commented on src/main/java/org/alliancegenome/curation_api/jobs/executors/LoadFileExecutor.java
> -				service.removeOrDeprecateNonUpdated(curie, dataProvider);
@markquintontulloch what may be better here is to pass the history object down, vs the md5 sum. And this method doesn't need to have the md5 passed in as it is available in the history object:  history.bulkLoadFile.md5Sum if there isn't a bulkLoadFile in the case of the API call with a list, then it can just be ignored.

2023-03-28 14:35 UTC, markquintontulloch commented on src/main/cliapp/src/containers/dataLoadsPage/DataLoadsComponent.js
> -			ret.push(<Column key="fmsDataType2" field="fmsDataType" header="Load Data Type" />);
This is for the manual loads and the data type was missing from the column until I made this change

2023-03-28 14:38 UTC, markquintontulloch commented on src/main/java/org/alliancegenome/curation_api/jobs/executors/LoadFileExecutor.java
> -				service.removeOrDeprecateNonUpdated(curie, dataProvider);
I tried that initially and it was throwing errors.  I’m not sure the back reference from history to file has been created at this point as I was getting a null pointer error on history.getBulkLoadFile()

2023-04-03 13:44 UTC, markquintontulloch commented
@oblodgett  - do you require any changes?  see comments above in response to your change requests

2023-04-04 12:10 UTC, oblodgett approved these changes

2023-04-04 12:10 UTC, merged